### ISSUE TITLE
add second C* node to monitoring dev environment

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/tlp-cluster#132]
right now we're able to spin up a single node, grafana, pometheus, and cassandra node.  our graphs are only showing the data from one C* node, meaning we can't catch issues that would only show up when running multiple nodes.

Let's make it a 2 node cluster.

**Comment by arodrime** [comment]
I did the work on this one here: https://github.com/thelastpickle/tlp-cluster/pull/135.

It's now open for review.

**Comment by rustyrazorblade** [comment]
I'm trying your branch.  I pruned all my docker containers, and it starts, but stress is throwing a ton of errors, and none of the dashboards load.
