### ISSUE TITLE
CPU graphs are probably wrong

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/tlp-cluster#147]
It's very unlikely that 6 nodes have the exact same CPU:

![image](https://user-images.githubusercontent.com/337872/66689768-24722300-ec41-11e9-8427-6d0f1c4e9dd5.png)

**Comment by arodrime** [comment]
I agree, this is wrong. I'll take this asap (I'll try tomorrow!)

**Comment by arodrime** [comment]
Created https://github.com/thelastpickle/tlp-cluster/pull/148 to solve this.

<img width="1655" alt="example cpu working" src="https://user-images.githubusercontent.com/1073404/67021180-8928f400-f0ff-11e9-8937-49c3600cff2d.png">
