### ISSUE TITLE
Generate auxiliary credentials (SSH keys, security group) automatically

### ISSUE THREAD

**Issue by nickbp** [thelastpickle/tlp-cluster#48]
cc @velo who originally recommended this

- when cluster is being built, generate one-off SSH keys, rather than requiring the user to provide their own SSH keypair
- similarly the security group could be a one-off

With the above, the user should only need to provide their AWS credentials, and if they've been using the `aws` CLI then those would already be available (see #45 ), making initial setup very simple.

This would also make it safer for the cluster creator to share the SSH keys to the cluster with a friend/coworker, as those keys would only be functional for that particular cluster.

**Comment by rustyrazorblade** [comment]
dupe of #41 and #42
