### ISSUE TITLE
build and install stress nodes

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/tlp-cluster#5]
tlp-cluster needs to be able to create stress nodes automatically.  Fortunately it's pretty damn easy - tlp-stress includes a docker-compose command to build a deb package.

By default, we should clone tlp-stress somewhere under `~/.tlp-cluster/` in order to generate the DEB package and copy it into `provisioning/stress`.  I'm thinking if the environment variable `TLP_STRESS_CUSTOM_DIR` is set we could build that directory instead for cases like mine where I want to use my own stress repo that might be working on a branch instead of master.  To me that's not the normal use case so let's keep things simple for 95% of folks who will use this.

When `tlp-cluster install` is run it will need to run install on the stress nodes, which i don't think it does yet.  That should be almost identical to how cassandra is installed, just on a different set of nodes.

**Comment by rustyrazorblade** [comment]
temp hack done in pr #33

**Comment by ossarga** [comment]
Monitoring provisioning has been implemented. Closing this.
