### ISSUE TITLE
support provisioning of monitoring box

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/tlp-cluster#7]
We should have the ability to provision a monitoring box which uses prometheus, grafana, elastic search and kibana (for logs).  This can be super simple, we don't need to build it all out with docker or anything, we can just create a new directory for install scripts called `provisioning/monitoring`. 

Each program should have it's own script to keep things organized.  

I'm setting up a separate issue for the actual dashboards, this is just to get the machines up and running.

We should enable 1 box by default so it's provisioned with every tlp-cluster workspace by default.

**Comment by rustyrazorblade** [comment]
Might be able to use this: https://github.com/yandex-money-tech/grafana-dashboard-plugin/blob/master/README.md

Or this: https://github.com/yandex-money-tech/grafana-dashboard-dsl/blob/master/README.md

**Comment by ossarga** [comment]
This has been done in pull request #33. Closing
