### ISSUE TITLE
move the ssh alias to a helpers.sh file

### ISSUE THREAD

**Issue by rustyrazorblade** [thelastpickle/tlp-cluster#92]
We recommend the user create an alias for SSH.  After the recommendation goes off the screen (for whatever reason) it's not obvious how to re-create it.

Let's move the alias to a helpers.sh file and recommend sourcing that file.  We can create other useful aliases such as `scp -F` and `sftp -F` to simplify the process.

The alias shows up after running the `up` subcommand, it's found in `com.thelastpickle.tlpcluster.commands.Up`.

**Comment by monsij** [comment]
@rustyrazorblade : What is to be moved into helpers.sh? I couldn't get it yet

**Comment by rustyrazorblade** [comment]
The alias is on line 42 of the class I listed above (Up).

Instead of just dropping the alias, in that spot we should say "please run source helpers.sh".  Helpers.sh should define the alias.

Please put helpers.sh under the com.thelastpickle.tlpcluster.commands resource directory and copy the resource using https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/IOUtils.html#copy-java.io.InputStream-java.io.OutputStream- to the current directory.

We already include commons-io in the gradle config, so it should be pretty straightforward.
